spring:
  application:
    name: example
  datasource:
    username: ${DATABASE_USER:postgres}
    password: ${DATABASE_PASSWORD:postgres}
    url: ${DATABASE_HOST_JDBC:jdbc:postgresql://localhost:5432}/order-service
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:/db/master.xml
  jpa:
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 90MB
      max-request-size: 90MB
server:
  port: ${SERVER_HTTP_PORT:8081}
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs