apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  selector:
    app: order-service-application
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service-application
  labels:
    app: order-service-application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service-application
  template:
    metadata:
      labels:
        app: order-service-application
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
    spec:
      containers:
        - name: order-service
          image: ghcr.io/hackathon-x-mode/backend/order:{{ .Values.image.tag }}
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
{{/*          env:*/}}
{{/*            - name: DATABASE_PASSWORD*/}}
{{/*              valueFrom:*/}}
{{/*                secretKeyRef:*/}}
{{/*                  name: postgres-postgresql*/}}
{{/*                  key: postgres-password*/}}
          envFrom:
            - configMapRef:
                name: common-service-envs
      imagePullSecrets:
        - name: regcred